<?php

namespace Database\Seeders;

use App\Models\Regency;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class RegencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        $regencies = [
        ['name'=>'Tarumajaya', 'city' => 'Bekasi'],
        ['name'=>'Tambun Utara', 'city' => 'Bekasi'],
        ['name'=>'Tambun Selatan', 'city' => 'Bekasi'],
        ['name'=>'Tambelang', 'city' => 'Bekasi'],
        ['name'=>'Sukawangi', 'city' => 'Bekasi'],
        ['name'=>'Sukatani', 'city' => 'Bekasi'],
        ['name'=>'Sukakarya', 'city' => 'Bekasi'],
        ['name'=>'Serang Baru', 'city' => 'Bekasi'],
        ['name'=>'Rawalumbu', 'city' => 'Bekasi'],
        ['name'=>'Pondok Melati', 'city' => 'Bekasi'],
        ['name'=>'Pondok Gede', 'city' => 'Bekasi'],
        ['name'=>'Pebayuran', 'city' => 'Bekasi'],
        ['name'=>'Mustika Jaya', 'city' => 'Bekasi'],
        ['name'=>'Muara Gembong', 'city' => 'Bekasi'],
        ['name'=>'Medan Satria', 'city' => 'Bekasi'],
        ['name'=>'Kedung Waringin', 'city' => 'Bekasi'],
        ['name'=>'Karangbahagia', 'city' => 'Bekasi'],
        ['name'=>'Jatiasih', 'city' => 'Bekasi'],
        ['name'=>'Jati Sampurna', 'city' => 'Bekasi'],
        ['name'=>'Cikarang Utara', 'city' => 'Bekasi'],
        ['name'=>'Cikarang Timur', 'city' => 'Bekasi'],
        ['name'=>'Cikarang Selatan', 'city' => 'Bekasi'],
        ['name'=>'Cikarang Pusat', 'city' => 'Bekasi'],
        ['name'=>'Cikarang Barat', 'city' => 'Bekasi'],
        ['name'=>'Cibitung', 'city' => 'Bekasi'],
        ['name'=>'Cibarusah', 'city' => 'Bekasi'],
        ['name'=>'Cabangbungin', 'city' => 'Bekasi'],
        ['name'=>'Bojongmangu', 'city' => 'Bekasi'],
        ['name'=>'Bekasi Utara', 'city' => 'Bekasi'],
        ['name'=>'Bekasi Timur', 'city' => 'Bekasi'],
        ['name'=>'Bekasi Selatan', 'city' => 'Bekasi'],
        ['name'=>'Bekasi Barat', 'city' => 'Bekasi'],
        ['name'=>'Bantar Gebang', 'city' => 'Bekasi'],
        ['name'=>'Babelan', 'city' => 'Bekasi'],
        ['name'=>'Tenjolaya', 'city' => 'Bogor'],
        ['name'=>'Tenjo', 'city' => 'Bogor'],
        ['name'=>'Tanjungsari', 'city' => 'Bogor'],
        ['name'=>'Tanah Sereal', 'city' => 'Bogor'],
        ['name'=>'Tamansari', 'city' => 'Bogor'],
        ['name'=>'Tajurhalang', 'city' => 'Bogor'],
        ['name'=>'Sukaraja', 'city' => 'Bogor'],
        ['name'=>'Sukamakmur', 'city' => 'Bogor'],
        ['name'=>'Sukajaya', 'city' => 'Bogor'],
        ['name'=>'Rumpin', 'city' => 'Bogor'],
        ['name'=>'Ranca Bungur', 'city' => 'Bogor'],
        ['name'=>'Parung Panjang', 'city' => 'Bogor'],
        ['name'=>'Parung', 'city' => 'Bogor'],
        ['name'=>'Pamijahan', 'city' => 'Bogor'],
        ['name'=>'Nanggung', 'city' => 'Bogor'],
        ['name'=>'Megamendung', 'city' => 'Bogor'],
        ['name'=>'Leuwisadeng', 'city' => 'Bogor'],
        ['name'=>'Leuwiliang', 'city' => 'Bogor'],
        ['name'=>'Klapanunggal', 'city' => 'Bogor'],
        ['name'=>'Kemang', 'city' => 'Bogor'],
        ['name'=>'Jonggol', 'city' => 'Bogor'],
        ['name'=>'Jasinga', 'city' => 'Bogor'],
        ['name'=>'Gunung Sindur', 'city' => 'Bogor'],
        ['name'=>'Gunung Putri', 'city' => 'Bogor'],
        ['name'=>'Dramaga', 'city' => 'Bogor'],
        ['name'=>'Citeureup', 'city' => 'Bogor'],
        ['name'=>'Ciseeng', 'city' => 'Bogor'],
        ['name'=>'Cisarua', 'city' => 'Bogor'],
        ['name'=>'Ciomas', 'city' => 'Bogor'],
        ['name'=>'Cileungsi', 'city' => 'Bogor'],
        ['name'=>'Cijeruk', 'city' => 'Bogor'],
        ['name'=>'Cigudeg', 'city' => 'Bogor'],
        ['name'=>'Cigombong', 'city' => 'Bogor'],
        ['name'=>'Cibungbulang', 'city' => 'Bogor'],
        ['name'=>'Cibinong', 'city' => 'Bogor'],
        ['name'=>'Ciawi', 'city' => 'Bogor'],
        ['name'=>'Ciampea', 'city' => 'Bogor'],
        ['name'=>'Cariu', 'city' => 'Bogor'],
        ['name'=>'Caringin', 'city' => 'Bogor'],
        ['name'=>'Bojonggede', 'city' => 'Bogor'],
        ['name'=>'Bogor Utara - Kota', 'city' => 'Bogor'],
        ['name'=>'Bogor Timur - Kota', 'city' => 'Bogor'],
        ['name'=>'Bogor Tengah - Kota', 'city' => 'Bogor'],
        ['name'=>'Bogor Selatan - Kota', 'city' => 'Bogor'],
        ['name'=>'Bogor Barat - Kota', 'city' => 'Bogor'],
        ['name'=>'Babakan Madang', 'city' => 'Bogor'],
        ['name'=>'Tapos', 'city' => 'Depok'],
        ['name'=>'Sukmajaya', 'city' => 'Depok'],
        ['name'=>'Sawangan', 'city' => 'Depok'],
        ['name'=>'Pancoran Mas', 'city' => 'Depok'],
        ['name'=>'Limo', 'city' => 'Depok'],
        ['name'=>'Cinere', 'city' => 'Depok'],
        ['name'=>'Cimanggis', 'city' => 'Depok'],
        ['name'=>'Cilodong', 'city' => 'Depok'],
        ['name'=>'Bojongsari', 'city' => 'Depok'],
        ['name'=>'Beji', 'city' => 'Depok'],
        ['name'=>'Tambora', 'city' => 'Jakarta Barat'],
        ['name'=>'Taman Sari', 'city' => 'Jakarta Barat'],
        ['name'=>'Palmerah', 'city' => 'Jakarta Barat'],
        ['name'=>'Kembangan', 'city' => 'Jakarta Barat'],
        ['name'=>'Kebon Jeruk', 'city' => 'Jakarta Barat'],
        ['name'=>'Kalideres', 'city' => 'Jakarta Barat'],
        ['name'=>'Grogol Petamburan', 'city' => 'Jakarta Barat'],
        ['name'=>'Cengkareng', 'city' => 'Jakarta Barat'],
        ['name'=>'Tanah Abang', 'city' => 'Jakarta Pusat'],
        ['name'=>'Senen', 'city' => 'Jakarta Pusat'],
        ['name'=>'Sawah Besar', 'city' => 'Jakarta Pusat'],
        ['name'=>'Menteng', 'city' => 'Jakarta Pusat'],
        ['name'=>'Kemayoran', 'city' => 'Jakarta Pusat'],
        ['name'=>'Johar Baru', 'city' => 'Jakarta Pusat'],
        ['name'=>'Gambir', 'city' => 'Jakarta Pusat'],
        ['name'=>'Cempaka Putih', 'city' => 'Jakarta Pusat'],
        ['name'=>'Tebet', 'city' => 'Jakarta Selatan'],
        ['name'=>'Setia Budi', 'city' => 'Jakarta Selatan'],
        ['name'=>'Pesanggrahan', 'city' => 'Jakarta Selatan'],
        ['name'=>'Pasar Minggu', 'city' => 'Jakarta Selatan'],
        ['name'=>'Pancoran', 'city' => 'Jakarta Selatan'],
        ['name'=>'Mampang Prapatan', 'city' => 'Jakarta Selatan'],
        ['name'=>'Kebayoran Lama', 'city' => 'Jakarta Selatan'],
        ['name'=>'Kebayoran Baru', 'city' => 'Jakarta Selatan'],
        ['name'=>'Jagakarsa', 'city' => 'Jakarta Selatan'],
        ['name'=>'Cilandak', 'city' => 'Jakarta Selatan'],
        ['name'=>'Pulo Gadung', 'city' => 'Jakarta Timur'],
        ['name'=>'Pasar Rebo', 'city' => 'Jakarta Timur'],
        ['name'=>'Matraman', 'city' => 'Jakarta Timur'],
        ['name'=>'Makasar', 'city' => 'Jakarta Timur'],
        ['name'=>'Kramat Jati', 'city' => 'Jakarta Timur'],
        ['name'=>'Jatinegara', 'city' => 'Jakarta Timur'],
        ['name'=>'Duren Sawit', 'city' => 'Jakarta Timur'],
        ['name'=>'Ciracas', 'city' => 'Jakarta Timur'],
        ['name'=>'Cipayung', 'city' => 'Jakarta Timur'],
        ['name'=>'Cakung', 'city' => 'Jakarta Timur'],
        ['name'=>'Tanjung Priok', 'city' => 'Jakarta Utara'],
        ['name'=>'Penjaringan', 'city' => 'Jakarta Utara'],
        ['name'=>'Pademangan', 'city' => 'Jakarta Utara'],
        ['name'=>'Koja', 'city' => 'Jakarta Utara'],
        ['name'=>'Kelapa Gading', 'city' => 'Jakarta Utara'],
        ['name'=>'Cilincing', 'city' => 'Jakarta Utara'],
        ['name'=>'Tirtamulya', 'city' => 'Karawang'],
        ['name'=>'Tirtajaya', 'city' => 'Karawang'],
        ['name'=>'Tempuran', 'city' => 'Karawang'],
        ['name'=>'Telukjambe Timur', 'city' => 'Karawang'],
        ['name'=>'Telukjambe Barat', 'city' => 'Karawang'],
        ['name'=>'Tegalwaru', 'city' => 'Karawang'],
        ['name'=>'Talagasari', 'city' => 'Karawang'],
        ['name'=>'Rengasdengklok', 'city' => 'Karawang'],
        ['name'=>'Rawamerta', 'city' => 'Karawang'],
        ['name'=>'Purwasari', 'city' => 'Karawang'],
        ['name'=>'Pedes', 'city' => 'Karawang'],
        ['name'=>'Pangkalan', 'city' => 'Karawang'],
        ['name'=>'Pakisjaya', 'city' => 'Karawang'],
        ['name'=>'Majalaya', 'city' => 'Karawang'],
        ['name'=>'Lemahabang', 'city' => 'Karawang'],
        ['name'=>'Kutawaluya', 'city' => 'Karawang'],
        ['name'=>'Kotabaru', 'city' => 'Karawang'],
        ['name'=>'Klari', 'city' => 'Karawang'],
        ['name'=>'Karawang Timur', 'city' => 'Karawang'],
        ['name'=>'Karawang Barat', 'city' => 'Karawang'],
        ['name'=>'Jayakerta', 'city' => 'Karawang'],
        ['name'=>'Jatisari', 'city' => 'Karawang'],
        ['name'=>'Cilebar', 'city' => 'Karawang'],
        ['name'=>'Cilamaya Wetan', 'city' => 'Karawang'],
        ['name'=>'Cilamaya Kulon', 'city' => 'Karawang'],
        ['name'=>'Cikampek', 'city' => 'Karawang'],
        ['name'=>'Cibuaya', 'city' => 'Karawang'],
        ['name'=>'Ciampel', 'city' => 'Karawang'],
        ['name'=>'Batujaya', 'city' => 'Karawang'],
        ['name'=>'Banyusari', 'city' => 'Karawang'],
        ['name'=>'Tigaraksa', 'city' => 'Tangerang'],
        ['name'=>'Teluknaga', 'city' => 'Tangerang'],
        ['name'=>'Tangerang', 'city' => 'Tangerang'],
        ['name'=>'Sukamulya', 'city' => 'Tangerang'],
        ['name'=>'Sukadiri', 'city' => 'Tangerang'],
        ['name'=>'Solear', 'city' => 'Tangerang'],
        ['name'=>'Sindang Jaya', 'city' => 'Tangerang'],
        ['name'=>'Sepatan Timur', 'city' => 'Tangerang'],
        ['name'=>'Sepatan', 'city' => 'Tangerang'],
        ['name'=>'Rajeg', 'city' => 'Tangerang'],
        ['name'=>'Pinang (Penang)', 'city' => 'Tangerang'],
        ['name'=>'Periuk', 'city' => 'Tangerang'],
        ['name'=>'Pasar Kemis', 'city' => 'Tangerang'],
        ['name'=>'Panongan', 'city' => 'Tangerang'],
        ['name'=>'Pakuhaji', 'city' => 'Tangerang'],
        ['name'=>'Pagedangan', 'city' => 'Tangerang'],
        ['name'=>'Neglasari', 'city' => 'Tangerang'],
        ['name'=>'Mekar Baru', 'city' => 'Tangerang'],
        ['name'=>'Mauk', 'city' => 'Tangerang'],
        ['name'=>'Legok', 'city' => 'Tangerang'],
        ['name'=>'Larangan', 'city' => 'Tangerang'],
        ['name'=>'Kronjo', 'city' => 'Tangerang'],
        ['name'=>'Kresek', 'city' => 'Tangerang'],
        ['name'=>'Kosambi', 'city' => 'Tangerang'],
        ['name'=>'Kemiri', 'city' => 'Tangerang'],
        ['name'=>'Kelapa Dua', 'city' => 'Tangerang'],
        ['name'=>'Karawaci', 'city' => 'Tangerang'],
        ['name'=>'Karang Tengah', 'city' => 'Tangerang'],
        ['name'=>'Jayanti', 'city' => 'Tangerang'],
        ['name'=>'Jatiuwung', 'city' => 'Tangerang'],
        ['name'=>'Jambe', 'city' => 'Tangerang'],
        ['name'=>'Gunung Kaler', 'city' => 'Tangerang'],
        ['name'=>'Curug', 'city' => 'Tangerang'],
        ['name'=>'Cisoka', 'city' => 'Tangerang'],
        ['name'=>'Cisauk', 'city' => 'Tangerang'],
        ['name'=>'Cipondoh', 'city' => 'Tangerang'],
        ['name'=>'Ciledug', 'city' => 'Tangerang'],
        ['name'=>'Cikupa', 'city' => 'Tangerang'],
        ['name'=>'Cibodas', 'city' => 'Tangerang'],
        ['name'=>'Benda', 'city' => 'Tangerang'],
        ['name'=>'Batuceper', 'city' => 'Tangerang'],
        ['name'=>'Balaraja', 'city' => 'Tangerang'],
        ['name'=>'Setu', 'city' => 'Tangerang Selatan'],
        ['name'=>'Serpong Utara', 'city' => 'Tangerang Selatan'],
        ['name'=>'Serpong', 'city' => 'Tangerang Selatan'],
        ['name'=>'Pondok Aren', 'city' => 'Tangerang Selatan'],
        ['name'=>'Pamulang', 'city' => 'Tangerang Selatan'],
        ['name'=>'Ciputat Timur', 'city' => 'Tangerang Selatan'],
        ['name'=>'Ciputat', 'city' => 'Tangerang Selatan'],
        ['name'=>'Bintaro', 'city' => 'Bintaro'],
        ['name'=>'Cibubur', 'city' => 'Cibubur'],
        ['name'=>'Depok', 'city' => 'Depok'],
        ['name'=>'Bekasi', 'city' => 'Bekasi'],
        ['name'=>'Bogor', 'city' => 'Bogor'],
      
        ];

        Regency::insert($regencies);
    }
}
